export const users = [
  {
    id: 1,
    name: "Candice Schiner",
    company: "Dell",
    role: "Frontend Developer",
    verified: false,
    status: "Active",
  },
  {
    id: 2,
    name: "John Doe",
    company: "TechCorp",
    role: "Backend Developer",
    verified: true,
    status: "Active",
  },
  {
    id: 3,
    name: "Alice Johnson",
    company: "WebTech",
    role: "UI Designer",
    verified: true,
    status: "Active",
  },
  {
    id: 4,
    name: "David Smith",
    company: "Innovate Inc.",
    role: "Fullstack Developer",
    verified: false,
    status: "Inactive",
  },
  {
    id: 5,
    name: "Emma Wilson",
    company: "TechGuru",
    role: "Product Manager",
    verified: true,
    status: "Active",
  },
  {
    id: 6,
    name: "James Brown",
    company: "CodeGenius",
    role: "QA Engineer",
    verified: false,
    status: "Active",
  },
  {
    id: 7,
    name: "Laura White",
    company: "SoftWorks",
    role: "UX Designer",
    verified: true,
    status: "Active",
  },
  {
    id: 8,
    name: "Michael Lee",
    company: "DevCraft",
    role: "DevOps Engineer",
    verified: false,
    status: "Active",
  },
  {
    id: 9,
    name: "Olivia Green",
    company: "WebSolutions",
    role: "Frontend Developer",
    verified: true,
    status: "Active",
  },
  {
    id: 10,
    name: "Robert Taylor",
    company: "DataTech",
    role: "Data Analyst",
    verified: false,
    status: "Active",
  },
];

export const navItems = [
  {
    title: "Dashboard",
    href: "/admin",
    icon: "dashboard",
    label: "Dashboard",
  },
  {
    title: "Berita",
    href: "/admin/berita",
    icon: "newspaper",
    label: "Berita",
  },
];

export const settingItems = [
  {
    title: "User",
    href: "/admin/user",
    icon: "user",
    label: "user",
  },
  {
    title: "Login",
    href: "/",
    icon: "login",
    label: "login",
  },
];


export const beritas = [
  {
    id: 1,
    judul: "HPN 2024, Bidang IKP Kom…ayasan Pondok Pesantren",
    slug: "hpn-2024-bidang-ikp-komi…ayasan-pondok-pesantren",
    gambar_sampul: "https://morowalikab.go.i…223-WA0042_thumbnail.jpg",
    isi_konten: '<p style="text-align: ju…gn: justify;">&nbsp;</p>',
    tags: "morowali, berita, inform…han, kabupaten morowali",
    tanggal_publish: "2024-02-23",
    jumlah_view: 1,
    tgl_buat: "2024-02-23 15:53:35",
    nama_publisher: "Maisarah"
  }, {
    id: 2,
    judul: "PJ Bupati Morowali, Rach…asar anggota Sat Pol PP",
    slug: "pj-bupati-morowali-rachm…asar-anggota-sat-pol-pp",
    gambar_sampul: "https://morowalikab.go.i…0at%2018-49-08%20(1).jpg",
    isi_konten: "<p><!-- [if gte mso 9]><…: IN;\">&nbsp;</span></p>",
    tags: "morowali, berita, inform…han, kabupaten morowali",
    tanggal_publish: "2024-02-22",
    jumlah_view: 69,
    tgl_buat: "2024-02-22 13:06:02",
    nama_publisher: "Tiya Lestari"
  },
  {
    id: 3,
    judul: "Pj Bupati Morowali, Rach…anan Perjanjian Kinerja",
    slug: "pj-bupati-morowali-rachm…anan-perjanjian-kinerja",
    gambar_sampul: "https://morowalikab.go.i…2-22%20at%2018-05-02.jpg",
    isi_konten: "<p><!-- [if gte mso 9]><…, Hasyim, Sp.</span></p>",
    tags: "morowali, berita, inform…han, kabupaten morowali",
    tanggal_publish: "2024-02-22",
    jumlah_view: 40,
    tgl_buat: "2024-02-22 12:32:44",
    nama_publisher: "Tiya Lestari"
  },
  {
    id: 4,
    judul: "Pj Bupati Morowali, Rach…sasi Formasi Tahun 2022",
    slug: "pj-bupati-morowali-rachm…sasi-formasi-tahun-2022",
    gambar_sampul: "https://morowalikab.go.i…%20at%207-53-40%20PM.jpg",
    isi_konten: "<p style=\"text-align: ju…impinan OPD lainnya.</p>",
    tags: "morowali, berita, inform…han, kabupaten morowali",
    tanggal_publish: "2024-02-22",
    jumlah_view: 67,
    tgl_buat: "2024-02-22 11:54:10",
    nama_publisher: "Ketut Suta"
  },
  {
    id: 5,
    judul: "Pj Bupati Morowali Membu…ungku Tengah Tahun 2024",
    slug: "r3r34t54t",
    gambar_sampul: "https://morowalikab.go.i…2-22%20at%2018-54-58.jpg",
    isi_konten: "<p style=\"text-align: ju… Kabupaten Morowali.</p>",
    tags: "morowali, berita, inform…han, kabupaten morowali",
    tanggal_publish: "2024-02-22",
    jumlah_view: 50,
    tgl_buat: "2024-02-22 11:51:55",
    nama_publisher: "Salsadila Rahim"
  },
  {
    id: 6,
    judul: "Wakili Pj Bupati Morowal…s di Desa Laantula Jaya",
    slug: "wakili-pj-bupati-morowal…s-di-desa-laantula-jaya",
    gambar_sampul: "https://morowalikab.go.i…012-38-38%20PM%20(1).jpg",
    isi_konten: "<p class=\"MsoNormal\" sty…gn: justify;\">&nbsp;</p>",
    tags: "morowali, berita, inform…han, kabupaten morowali",
    tanggal_publish: "2024-02-22",
    jumlah_view: 9,
    tgl_buat: "2024-02-22 10:10:22",
    nama_publisher: "Maisarah"
  },
  {
    id: 7,
    judul: "Wakili Pj. Bupati Morowa…ian Sulteng di Morowali",
    slug: "wakili-pj-bupati-morowal…ian-sulteng-di-morowali",
    gambar_sampul: "https://morowalikab.go.i…2-22%20at%2010-56-29.jpg",
    isi_konten: "<p><span style=\"color: #… perwakilan peserta.</p>",
    tags: "morowali, berita, inform…han, kabupaten morowali",
    tanggal_publish: "2024-02-22",
    jumlah_view: 63,
    tgl_buat: "2024-02-22 04:17:41",
    nama_publisher: "Salsadila Rahim"
  },
  {
    id: 8,
    judul: "Tingkatkan SDM Aparatur,…endampingan RSUD Undata",
    slug: "tingkatkan-sdm-aparatur-…endampingan-rsud-undata",
    gambar_sampul: "https://morowalikab.go.i…2-21%20at%2019-17-09.jpg",
    isi_konten: "<p class=\"MsoNormal\" sty…r Elsa, S.Si.</span></p>",
    tags: "morowali, berita, inform…han, kabupaten morowali",
    tanggal_publish: "2024-02-21",
    jumlah_view: 51,
    tgl_buat: "2024-02-21 12:23:56",
    nama_publisher: "helman kaimu"
  },
  {
    id: 9,
    judul: "Wakili Pj Bupati Morowal…bijakan Merdeka Belajar",
    slug: "wakili-pj-bupati-morowal…bijakan-merdeka-belajar",
    gambar_sampul: "https://morowalikab.go.i…2-21%20at%2017-07-41.jpg",
    isi_konten: "<p dir=\"ltr\" style=\"line…gan lainnya. </span></p>",
    tags: "morowali, berita, inform…han, kabupaten morowali",
    tanggal_publish: "2024-02-21",
    jumlah_view: 95,
    tgl_buat: "2024-02-21 09:35:35",
    nama_publisher: "Octaviana Latong"
  },
  {
    id: 10,
    judul: "HPN 2024, Bidang IKP Kom…ayasan Pondok Pesantren",
    slug: "hpn-2024-bidang-ikp-komi…ayasan-pondok-pesantren",
    gambar_sampul: "https://morowalikab.go.i…223-WA0042_thumbnail.jpg",
    isi_konten: '<p style="text-align: ju…gn: justify;">&nbsp;</p>',
    tags: "morowali, berita, inform…han, kabupaten morowali",
    tanggal_publish: "2024-02-23",
    jumlah_view: 1,
    tgl_buat: "2024-02-23 15:53:35",
    nama_publisher: "Maisarah"
  }, {
    id: 11,
    judul: "PJ Bupati Morowali, Rach…asar anggota Sat Pol PP",
    slug: "pj-bupati-morowali-rachm…asar-anggota-sat-pol-pp",
    gambar_sampul: "https://morowalikab.go.i…0at%2018-49-08%20(1).jpg",
    isi_konten: "<p><!-- [if gte mso 9]><…: IN;\">&nbsp;</span></p>",
    tags: "morowali, berita, inform…han, kabupaten morowali",
    tanggal_publish: "2024-02-22",
    jumlah_view: 69,
    tgl_buat: "2024-02-22 13:06:02",
    nama_publisher: "Tiya Lestari"
  },
  {
    id: 12,
    judul: "Pj Bupati Morowali, Rach…anan Perjanjian Kinerja",
    slug: "pj-bupati-morowali-rachm…anan-perjanjian-kinerja",
    gambar_sampul: "https://morowalikab.go.i…2-22%20at%2018-05-02.jpg",
    isi_konten: "<p><!-- [if gte mso 9]><…, Hasyim, Sp.</span></p>",
    tags: "morowali, berita, inform…han, kabupaten morowali",
    tanggal_publish: "2024-02-22",
    jumlah_view: 40,
    tgl_buat: "2024-02-22 12:32:44",
    nama_publisher: "Tiya Lestari"
  },
  {
    id: 13,
    judul: "Pj Bupati Morowali, Rach…anan Perjanjian Kinerja",
    slug: "pj-bupati-morowali-rachm…anan-perjanjian-kinerja",
    gambar_sampul: "https://morowalikab.go.i…2-22%20at%2018-05-02.jpg",
    isi_konten: "<p><!-- [if gte mso 9]><…, Hasyim, Sp.</span></p>",
    tags: "morowali, berita, inform…han, kabupaten morowali",
    tanggal_publish: "2024-02-22",
    jumlah_view: 40,
    tgl_buat: "2024-02-22 12:32:44",
    nama_publisher: "Tiya Lestari"
  },
  {
    id: 14,
    judul: "Pj Bupati Morowali, Rach…sasi Formasi Tahun 2022",
    slug: "pj-bupati-morowali-rachm…sasi-formasi-tahun-2022",
    gambar_sampul: "https://morowalikab.go.i…%20at%207-53-40%20PM.jpg",
    isi_konten: "<p style=\"text-align: ju…impinan OPD lainnya.</p>",
    tags: "morowali, berita, inform…han, kabupaten morowali",
    tanggal_publish: "2024-02-22",
    jumlah_view: 67,
    tgl_buat: "2024-02-22 11:54:10",
    nama_publisher: "Ketut Suta"
  },
  {
    id: 15,
    judul: "Pj Bupati Morowali Membu…ungku Tengah Tahun 2024",
    slug: "r3r34t54t",
    gambar_sampul: "https://morowalikab.go.i…2-22%20at%2018-54-58.jpg",
    isi_konten: "<p style=\"text-align: ju… Kabupaten Morowali.</p>",
    tags: "morowali, berita, inform…han, kabupaten morowali",
    tanggal_publish: "2024-02-22",
    jumlah_view: 50,
    tgl_buat: "2024-02-22 11:51:55",
    nama_publisher: "Salsadila Rahim"
  },
  {
    id: 16,
    judul: "Wakili Pj Bupati Morowal…s di Desa Laantula Jaya",
    slug: "wakili-pj-bupati-morowal…s-di-desa-laantula-jaya",
    gambar_sampul: "https://morowalikab.go.i…012-38-38%20PM%20(1).jpg",
    isi_konten: "<p class=\"MsoNormal\" sty…gn: justify;\">&nbsp;</p>",
    tags: "morowali, berita, inform…han, kabupaten morowali",
    tanggal_publish: "2024-02-22",
    jumlah_view: 9,
    tgl_buat: "2024-02-22 10:10:22",
    nama_publisher: "Maisarah"
  },
  {
    id: 17,
    judul: "Wakili Pj. Bupati Morowa…ian Sulteng di Morowali",
    slug: "wakili-pj-bupati-morowal…ian-sulteng-di-morowali",
    gambar_sampul: "https://morowalikab.go.i…2-22%20at%2010-56-29.jpg",
    isi_konten: "<p><span style=\"color: #… perwakilan peserta.</p>",
    tags: "morowali, berita, inform…han, kabupaten morowali",
    tanggal_publish: "2024-02-22",
    jumlah_view: 63,
    tgl_buat: "2024-02-22 04:17:41",
    nama_publisher: "Salsadila Rahim"
  },
  {
    id: 18,
    judul: "Tingkatkan SDM Aparatur,…endampingan RSUD Undata",
    slug: "tingkatkan-sdm-aparatur-…endampingan-rsud-undata",
    gambar_sampul: "https://morowalikab.go.i…2-21%20at%2019-17-09.jpg",
    isi_konten: "<p class=\"MsoNormal\" sty…r Elsa, S.Si.</span></p>",
    tags: "morowali, berita, inform…han, kabupaten morowali",
    tanggal_publish: "2024-02-21",
    jumlah_view: 51,
    tgl_buat: "2024-02-21 12:23:56",
    nama_publisher: "helman kaimu"
  },
  {
    id: 19,
    judul: "Wakili Pj Bupati Morowal…bijakan Merdeka Belajar",
    slug: "wakili-pj-bupati-morowal…bijakan-merdeka-belajar",
    gambar_sampul: "https://morowalikab.go.i…2-21%20at%2017-07-41.jpg",
    isi_konten: "<p dir=\"ltr\" style=\"line…gan lainnya. </span></p>",
    tags: "morowali, berita, inform…han, kabupaten morowali",
    tanggal_publish: "2024-02-21",
    jumlah_view: 95,
    tgl_buat: "2024-02-21 09:35:35",
    nama_publisher: "Octaviana Latong"
  },
];