import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/components/layout/providers";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  // const session = await getServerSession();
  return (
    <html lang="en">
      <body className={`${inter.className} overflow-hidden`}>
        {/* <Providers session={session}> */}
        <Providers>
          <Toaster />
          {children}
        </Providers>
      </body>
    </html>
  );
}

